apiVersion: cert-manager.io/v1

kind: Certificate

metadata:
  name: danielweigel-net-tls
spec:
  secretName: danielweigel-net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: danielweigel.net
  dnsNames:
    - danielweigel.net
    - www.danielweigel.net
